name: sample-push

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:
    inputs:
      hello:
        description: '...'
        default: 'hi'
        required: true

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: 'Job 1'
        run: echo "${{ github.event.inputs.hello }}, World"
