name: sample-push

on:
  push:

env:
  HELLO: 'Hello'

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: 'Job 1'
        if: ${{ env.HELLO == 'hi' }}
        run: echo "${{ env.HELLO }}, World"
