name: sample-push

on:
  push:

jobs:
  job-1:
    runs-on: macos-latest

    steps:
      - name: 'Job 1'
        run: echo "Hello, World"

  job-2:
    runs-on: macos-latest

    steps:
      - name: 'Job 2'
        run: echo "Hello, World, 2"
